// COMMON
export const GET_WALLET_API = "GET_WALLET_API";
export const GET_HISTORY_API = "GET_HISTORY_API";
export const GET_MARKET_API = "GET_MARKET_API";

export const CRYPTO_ADD_TO_WALLET = "CRYPTO_ADD_TO_WALLET";
export const CRYPTO_REMOVE_FROM_WALLET = "CRYPTO_REMOVE_FROM_WALLET";

export const BALANCE_DECREASE = "BALANCE_DECREASE";
export const BALANCE_INCREASE = "BALANCE_INCREASE";

export const WALLET_SET = "WALLET_SET";

export const CRYPTO_ADD_TO_HISTORY = "CRYPTO_ADD_TO_HISTORY";



